language: c++
script: dpkg-buildpackage -b -us -uc

install:
   - sudo apt-get install omake ocaml protobuf-compiler libprotobuf-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev libdir-self-perl

# whitelist
branches:
   only:
      - master
      - /.*\/staging/
